cron.status: "0 * * * * ?"

management:
  endpoint.health.probes.enabled: true
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true

otel:
  instrumentation.micrometer.enabled: false
  logs.exporter: none
  metrics.exporter: none
  service.name: "kafka-producer"
  traces.exporter: none

spring:
  application.name: kafka-producer
  jpa.hibernate.ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    listener.observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties.enable.idempotence: false
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties.schema.registry.url: http://localhost:9081
    template.observation-enabled: true
    topic.status: status.topic
  profiles.default: local