cron.status: "0 * * * * ?"

management:
  endpoint.health.probes.enabled: true
  endpoints.web.exposure.include: health, metrics
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true

otel:
  instrumentation.micrometer.enabled: true
  logs.exporter: none
  metrics.exporter: none
  service.name: "kafka-producer"
  traces.exporter: none

server.port: 5000

spring:
  application.name: kafka-producer
  jpa.hibernate.ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    listener.observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties.enable.idempotence: false
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template.observation-enabled: true
    topic.status: order.status
  profiles.default: local
