receivers:
  # Data sources: traces
  jaeger:
    protocols:
      grpc:
        endpoint: localhost:4317
      thrift_binary:
      thrift_compact:
      thrift_http:

  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

  # Data sources: metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: otel-collector
          scrape_interval: 5s
          static_configs:
            - targets: [ localhost:8888 ]

processors:
  batch:

extensions:
  health_check:
  pprof:
  zpages:

exporters:
  # Data sources: traces
  otlp:
    endpoint: jaeger-server:4317
    tls:
      insecure: true
  # Data sources: metrics
  prometheus:
    endpoint: "localhost:9090"

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, prometheus]
    logs:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ otlp ]