services:
  kafka:
    container_name: kafka
    image: apache/kafka-native:latest
    profiles:
      - all
      - global
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    labels:
      org.springframework.boot.service-connection: kafka
    environment:
      CLUSTER_ID: "WMZu34KEuahe6jZ7imNSx5"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093,INTERNAL://kafka:9094
      KAFKA_LOG_CLEANER_MAX_COMPACTION_LAG_MS: 1
      KAFKA_NODE_ID: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_SSL_CLIENT_AUTH: "none"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    profiles:
      - all
      - global
    ports:
      - "9080:8080"
    labels:
      org.springframework.boot.ignore: true
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9094
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema:8081
    healthcheck:
      test: wget -q0- http://localhost:9090/actuator/health || exit 1
      interval: 1s
      timeout: 1s
      retries: 10
    stop_signal: SIGKILL
